:document-title: Feature Update - Mobile ABQ
= Feature Update - Mobile ABQ
:toclevels: 2
:leveloffset: +1
:icons: font
:source-highlighter: coderay
:experimental:

= Feature Update - Mobile ABQ
Coming with Zimbra 8.8.9 (Curie Release) we have a new feature called [blue]_Allow/Block/Quarantine_ (ABQ), which is an access control feature and will be included in the Mobile NG module of Zimbra Network Edition and in the Mobile+ module of Zimbra Suite Plus.

== Feature Description

The `Allow/Block/Quarantine` (ABQ) feature allows for granular access control of mobile devices connecting to the server. It's a "pre-emptive" type of security feature, meaning that it acts upon the first connection to the server and it's made to ensure that only authorized devices can finalize the synchronization with the server.

The ABQ feature is composed of three main logical components:

* a Device Control List
* an Authorization Engine
* a set of CLI tools

=== Device Control List
A `Device Control list` holds the information about allowed devices within the NG config engine. Devices can be added to the Device Control List via CLI based on their [red]_Device ID_.

[NOTE]
icon:comment[] The meaning of [red]_Device ID_ needs to be clarified with an example. How does the admin find it?

=== Authorization Engine
The `Authorization Engine` takes care of checking new devices against the Device Control List and setting their ABQ status to the appropriate value.

=== CLI Toolset
The `CLI Toolset` allows administrators to interact with the device control list and with the synchronization status of a device, specifically:

* Display the Device Control List
* Display all Quarantined and Blocked Devices
* Add one or more devices to the Device Control List
* Move a device from “Quarantine” to “Allowed” or “Blocked”
* Change the synchronization status of a device

TIP: ABQ list is about controlling which devices (device type/id) are allowed to connect while Exchange ActiveSync policies allow you to limit device access by capabilities.

== ABQ Modes
The ABQ feature is triggered for the first time for every mobile device, every time a mobile device tries to synchronize with the server. This can be set to one of four possible modes: "Permissive", "Interactive", "Strict” and "Disabled".

[TIP]
icon:comment[] ABQ mode is a global setting.

* *Permissive* mode:
+
The Authorization Engine is not active, so after authenticating the user and checking its account status for safety reasons, the synchronization will continue. It is still possible to block specific devices but non-blocked devices will always be allowed to sync.

* *Interactive* mode:
+
After authenticating the user and checking its account status for safety reasons, the Device Control system will check the "Device ID" sent by the device against the list of allowed devices:

** if the device is in the "allowed" list the synchronization will continue.
** if the device is not in the “allowed” list the synchronization will be paused, a dummy email
notifying the user of its "Quarantine" status will be sent and the connection will be set to "Quarantine" status.

+
Administrators can be notified at regular intervals, and every notification email will only include new Quarantined devices. They will then be able to allow or deny the synchronization for each device using the appropriate CLI tools.

* *Strict* mode:
+
After authenticating the user and checking its account status for safety reasons, the Device Control system will check the "Device ID" sent by the device against the list of allowed devices:

** if the device is in the “allowed” list the synchronization will continue
** if the device is not in the “allowed” list the synchronization will be put in "Blocked" status, no data
will be synchronized and a dummy email notifying the user of its "Blocked" status will be sent.

* *Disabled* mode:
+
ABQ is disabled, no checks are triggered and no policies are enforced.

== ABQ Mode Control
The current mode can be checked by running the following command:
[source, bash]
----
zxsuite config global get attribute abqMode
----

The ABQ mode can be changed running the following command:
[source, bash]
----
zxsuite config global set attribute abqMode value [Permissive|Interactive|Strict|Disabled]
----

== Dummy data

The feature makes use of “Dummy emails” and a “Dummy mailbox” to put devices on hold while waiting for authorization (Interactive Mode) or to notify their “Blocked” status (Permissive Mode, Interactive Mode and Strict Mode).

The Dummy Mailbox is a _virtual_ mailbox consisting of only an [blue]*Inbox* folder that will be synchronized to the device while this is in either Quarantine or Block status containing dummy emails describing the device's status. Dummy Emails are _predefined email messages_ that are synchronized to a device in Quarantine or Block status to alert the user. Whenever the ABQ status of a device is changed, the device's sync state will be reset.

[NOTE]
icon:comment[] Add information regarding predefined email messages

This was designed to make sure the user knows what’s happening, the alternative being forcing the synchronization to fail with no descriptive response for the user itself – which would likely cause a huge overhead on support calls.

== Notifications

Administrators can be notified via email of quarantined devices at a specific interval defined by the "abqNotificationsInterval" NG configuration attribute, expressed in milliseconds.

The interval can be checked by running the following command:
[source, bash]
----
zxsuite config global get attribute abqNotificationsInterval
----

The interval can be changed running the following command:
[source, bash]
----
zxsuite config global set attribute abqNotificationsInterval value [delay in milliseconds]
----

By default, the "abqNotificationsInterval" is set to 0 - meaning that no notifications will be delivered.

== ABQ Service Status
The ABQ service status can be checked running the following command:
[source, bash]
----
zxsuite mobile getServices
----

The service can be stopped or started using the default service control of the Mobile NG module:
[source, bash]
----
zxsuite mobile doStartService abq
zxsuite mobile doStopService abq
----

When mode is Disabled ABQ service won't automatically start and devices are always allowed to sync
